### PR TITLE
Use 4 space indentation

### PR DESCRIPTION
**Pull request by alteous**
</zealotry>

### CODE REVIEW

**Comment by bwasty** [comment]
Well, JavaScript has converged on 2 spaces in the last few years, so I use that for new projects.

**Comment by bwasty** [comment]
Well, JavaScript land has kind of converged to 2 spaces, so I stick with it for new projects:
https://github.com/airbnb/javascript#whitespace
https://github.com/felixge/node-style-guide#2-spaces-for-indentation
https://standardjs.com/#the-rules
https://google.github.io/styleguide/jsguide.html#formatting-block-indentation
https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style

Given the high amount of callbacks, it's actually quite nice to have less indentation sometimes.

**Comment by alteous** [comment]
Boo! :smile:

**Comment by alteous** [comment]
I've changed the title because it's showing up on my profile page and I don't want recruiters to get a wrong impression! If it wasn't already obvious, the original title was a joke. :smile:

**Pull request closed without merging**
